-- Jalankan di phpMyAdmin > db_pkl > tab SQL

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS pengumuman;
DROP TABLE IF EXISTS penilaian;
DROP TABLE IF EXISTS logbook;
DROP TABLE IF EXISTS pendaftaran;
DROP TABLE IF EXISTS perusahaan;
DROP TABLE IF EXISTS pembimbing;
DROP TABLE IF EXISTS siswa;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS pkl;
DROP TABLE IF EXISTS pendaftaran_pkl;
DROP TABLE IF EXISTS profile;

SET FOREIGN_KEY_CHECKS = 1;
